### PR TITLE
Add support of terraform >=0.12

### PR DESCRIPTION
**Pull request by rvadim**

### CODE REVIEW

**Comment by mr-smithers-excellent** [comment]
Would be great to get this merged as the current format is not 0.12 compatible.

**Comment by sugdyzhekov** [comment]
@rvadim please update README.md

**Review by sugdyzhekov — CHANGES_REQUESTED** [review]
Please add corresponding changes to README.md

**Comment by rvadim** [comment]
README updated, thank you :+1:

**Review by sugdyzhekov — APPROVED** [review]
Looks good

**Pull request merged**
